credentials:
  usernames:
    Kimagut:
      email: briankimagut@gmail.com
      name: Brian Kimagut
      password: 'Kimz123'  # This should be a hashed password
cookie:
  expiry_days: 0
  key: cookie_signature_key
  name: cookie_name
preauthorized:
  usernames:
  - Kimagut
